# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/image_processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/image_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/image_processing.proto\x12\x0fimageprocessing\"\xaa\x01\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12.\n\noperations\x18\x02 \x03(\x0b\x32\x1a.imageprocessing.Operation\x12\x1a\n\x12generate_thumbnail\x18\x03 \x01(\x08\x12:\n\x10thumbnail_params\x18\x04 \x01(\x0b\x32 .imageprocessing.ThumbnailParams\"\xd7\x01\n\tOperation\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.imageprocessing.OperationType\x12\x34\n\rrotate_params\x18\x02 \x01(\x0b\x32\x1d.imageprocessing.RotateParams\x12\x34\n\rresize_params\x18\x03 \x01(\x0b\x32\x1d.imageprocessing.ResizeParams\x12\x30\n\x0b\x66lip_params\x18\x04 \x01(\x0b\x32\x1b.imageprocessing.FlipParams\"\x1d\n\x0cRotateParams\x12\r\n\x05\x61ngle\x18\x01 \x01(\x02\"-\n\x0cResizeParams\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"?\n\nFlipParams\x12\x31\n\tdirection\x18\x01 \x01(\x0e\x32\x1e.imageprocessing.FlipDirection\"8\n\x0fThumbnailParams\x12\x11\n\tmax_width\x18\x01 \x01(\x05\x12\x12\n\nmax_height\x18\x02 \x01(\x05\"v\n\rImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fprocessed_image\x18\x02 \x01(\x0c\x12\x11\n\tthumbnail\x18\x03 \x01(\x0c\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x11\n\tmime_type\x18\x05 \x01(\t*@\n\rOperationType\x12\n\n\x06ROTATE\x10\x00\x12\n\n\x06RESIZE\x10\x01\x12\x08\n\x04\x46LIP\x10\x02\x12\r\n\tGRAYSCALE\x10\x03*-\n\rFlipDirection\x12\x0e\n\nHORIZONTAL\x10\x00\x12\x0c\n\x08VERTICAL\x10\x01\x32_\n\x0eImageProcessor\x12M\n\x0cProcessImage\x12\x1d.imageprocessing.ImageRequest\x1a\x1e.imageprocessing.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.image_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONTYPE']._serialized_start=761
  _globals['_OPERATIONTYPE']._serialized_end=825
  _globals['_FLIPDIRECTION']._serialized_start=827
  _globals['_FLIPDIRECTION']._serialized_end=872
  _globals['_IMAGEREQUEST']._serialized_start=50
  _globals['_IMAGEREQUEST']._serialized_end=220
  _globals['_OPERATION']._serialized_start=223
  _globals['_OPERATION']._serialized_end=438
  _globals['_ROTATEPARAMS']._serialized_start=440
  _globals['_ROTATEPARAMS']._serialized_end=469
  _globals['_RESIZEPARAMS']._serialized_start=471
  _globals['_RESIZEPARAMS']._serialized_end=516
  _globals['_FLIPPARAMS']._serialized_start=518
  _globals['_FLIPPARAMS']._serialized_end=581
  _globals['_THUMBNAILPARAMS']._serialized_start=583
  _globals['_THUMBNAILPARAMS']._serialized_end=639
  _globals['_IMAGERESPONSE']._serialized_start=641
  _globals['_IMAGERESPONSE']._serialized_end=759
  _globals['_IMAGEPROCESSOR']._serialized_start=874
  _globals['_IMAGEPROCESSOR']._serialized_end=969
# @@protoc_insertion_point(module_scope)

